version: "3.9"
services:
  db:
    image: postgres:13-alpine3.15
    volumes:
        - ./tmp/db:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: password
    ports:
        - 5433:5432
  web: &app
    build: .
    command: sh -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp:cached                     # コンテナとローカルのコードを同期
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
      - packs:/myapp/public/packs
    ports:
        - 3000:3000
    depends_on:
        - db
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: password
        WEBPACKER_DEV_SERVER_HOST: webpack-dev-server
    tty: true
    stdin_open: true
  webpack-dev-server:
    <<: *app
    command: ./bin/webpack-dev-server
    volumes:
      - .:/myapp:cached
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
      - packs:/myapp/public/packs
    environment:
        - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    ports:
        - "3035:3035"
    depends_on:
        - web
volumes:
  postgres:
  bundle:
  node_modules:
  packs:
